### ISSUE TITLE
[FEATURE REQUEST] Option to lock widget size

### ISSUE THREAD

**Issue by demfabris** [sakithb/media-controls#48]
Currently the only way to have a consistent size is to decrease the widget length by a minimal, which doesn't look ideal.
Please add a switch to lock a widget size to a fixed length so that it doesn't resize and move buttons around on every song change

**Comment by Deottive** [comment]
I dont think this is possible because a song which for example you are playing on Spotify will not have the same length of letters, So for example 

![image](https://user-images.githubusercontent.com/71910027/151475599-7a248b50-b3a7-4377-baca-da3e73f1d05d.png)
I have set the size for aroudn 300 and this is the max it goes but as I change the song the size of title will also change 
![image](https://user-images.githubusercontent.com/71910027/151475715-1ff9130a-aa8e-4cef-8e95-706f78def604.png)
In this the song is a lot smaller so, I dont think this is possible if you get my point

**Comment by ChrisLauinger77** [comment]
Same as #37
